//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerMultimedaPlayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class calma_listesi_kart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calma_listesi_kart()
        {
            this.calma_liste_detay = new HashSet<calma_liste_detay>();
        }
    
        public int id { get; set; }
        public string liste_adi { get; set; }
        public Nullable<int> sil_id { get; set; }
        public Nullable<System.DateTime> olusturma_tarihi { get; set; }
        public Nullable<System.DateTime> guncelleme_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calma_liste_detay> calma_liste_detay { get; set; }
    }
}
